package export

import (
	"bytes"
	"fmt"

	"gopkg.in/yaml.v3"

	"github.com/andronaft/k8s-guardian/internal/custom"
	"github.com/andronaft/k8s-guardian/internal/rules"
)

// Kyverno renders one Kyverno ClusterPolicy per rule using CEL validation
// (Kyverno >= 1.11), with the same expressions as the VAP export.
// Kyverno has no "warn" action: warnings and info map to Audit (policy
// reports) and errors to Enforce, unless opts.Action overrides it.
func Kyverno(builtin []string, docs []custom.Document, opts Options) (*Result, error) {
	if opts.ExcludeNamespaces == nil {
		opts.ExcludeNamespaces = []string{"kube-system"}
	}
	res := &Result{}
	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Generated by k8s-guardian export kyverno: Kyverno ClusterPolicies with CEL validation (Kyverno >= 1.11).")
	fmt.Fprintln(&buf, "# Apply with: kubectl apply -f <this file>   or test with: kyverno apply <this file> --resource <manifest>")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	for _, p := range collect(builtin, docs, res) {
		action := "Audit"
		switch opts.Action {
		case "Deny":
			action = "Enforce"
		case "Warn", "Audit":
		default:
			if p.severity == rules.Error {
				action = "Enforce"
			}
		}
		var krules []any
		for _, c := range p.checks() {
			name := "check"
			if c.suffix != "" {
				name = c.suffix
			}
			celSpec := map[string]any{"expressions": []any{map[string]any{"expression": c.expr, "message": p.text()}}}
			if c.variables != nil {
				celSpec["variables"] = c.variables
			}
			krules = append(krules, map[string]any{
				"name": name,
				"match": map[string]any{"any": []any{map[string]any{"resources": map[string]any{
					"kinds": c.kinds, "operations": []string{"CREATE", "UPDATE"},
				}}}},
				"exclude": map[string]any{"any": []any{map[string]any{"resources": map[string]any{
					"namespaces": opts.ExcludeNamespaces,
				}}}},
				"validate": map[string]any{"failureAction": action, "cel": celSpec},
			})
		}
		obj := map[string]any{
			"apiVersion": "kyverno.io/v1", "kind": "ClusterPolicy",
			"metadata": map[string]any{
				"name":   p.resourceName(),
				"labels": map[string]string{"app.kubernetes.io/managed-by": "k8s-guardian", "k8s-guardian.io/rule": p.id},
				"annotations": map[string]string{
					"policies.kyverno.io/title":       p.id + " " + p.name,
					"policies.kyverno.io/description": p.description,
					"policies.kyverno.io/severity":    kyvernoSeverity(p.severity),
					// Rules already cover Pods, workloads and CronJobs explicitly.
					"pod-policies.kyverno.io/autogen-controllers": "none",
				},
			},
			"spec": map[string]any{"background": true, "rules": krules},
		}
		if err := enc.Encode(obj); err != nil {
			return nil, err
		}
		res.Count++
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	res.YAML = buf.Bytes()
	return res, nil
}

func kyvernoSeverity(s rules.Severity) string {
	switch s {
	case rules.Error:
		return "high"
	case rules.Warning:
		return "medium"
	}
	return "low"
}
