package export

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/andronaft/k8s-guardian/internal/custom"
	"github.com/andronaft/k8s-guardian/internal/rules"
)

type gr struct{ group, resource string }

var kindResources = map[string]gr{
	"Pod": {"", "pods"}, "ReplicationController": {"", "replicationcontrollers"},
	"Deployment": {"apps", "deployments"}, "StatefulSet": {"apps", "statefulsets"},
	"DaemonSet": {"apps", "daemonsets"}, "ReplicaSet": {"apps", "replicasets"},
	"Job": {"batch", "jobs"}, "CronJob": {"batch", "cronjobs"},
	"Service": {"", "services"}, "ConfigMap": {"", "configmaps"}, "Secret": {"", "secrets"},
	"Namespace": {"", "namespaces"}, "ServiceAccount": {"", "serviceaccounts"},
	"PersistentVolumeClaim": {"", "persistentvolumeclaims"},
	"Ingress":               {"networking.k8s.io", "ingresses"}, "NetworkPolicy": {"networking.k8s.io", "networkpolicies"},
	"HorizontalPodAutoscaler": {"autoscaling", "horizontalpodautoscalers"},
	"PodDisruptionBudget":     {"policy", "poddisruptionbudgets"},
	"Role":                    {"rbac.authorization.k8s.io", "roles"}, "RoleBinding": {"rbac.authorization.k8s.io", "rolebindings"},
	"ClusterRole": {"rbac.authorization.k8s.io", "clusterroles"}, "ClusterRoleBinding": {"rbac.authorization.k8s.io", "clusterrolebindings"},
}

// Workload families share the location of their pod spec, so each gets its
// own policy with a precisely typed podSpec variable.
type family struct {
	suffix  string
	kinds   []string
	podSpec string
}

var families = []family{
	{"pods", []string{"Pod"}, "object.spec"},
	{"workloads", []string{"Deployment", "StatefulSet", "DaemonSet", "ReplicaSet", "ReplicationController", "Job"}, "object.spec.template.spec"},
	{"cronjobs", []string{"CronJob"}, "object.spec.jobTemplate.spec.template.spec"},
}

const containersExpr = `(has(variables.podSpec.initContainers) ? variables.podSpec.initContainers : []) + (has(variables.podSpec.containers) ? variables.podSpec.containers : [])`

// Options controls the export.
type Options struct {
	// Action overrides the severity mapping (error→Deny, warning→Warn,
	// info→Audit) when set to Deny, Warn or Audit.
	Action string
	// ExcludeNamespaces are never enforced (default: kube-system).
	ExcludeNamespaces []string
}

// policy is an exportable rule: CEL checks for one or more scopes.
type policy struct {
	id, name, description, message string
	severity                       rules.Severity
	kinds                          []string // resource-scope kinds
	scope                          string   // resource | pod | container
	expr                           string   // CEL, relative to object / variables.podSpec / container variable c
}

// Result of an export.
type Result struct {
	YAML    []byte
	Count   int      // number of ValidatingAdmissionPolicies
	Skipped []string // rules that could not be exported, with reasons
}

// VAP renders ValidatingAdmissionPolicy + Binding pairs for the given
// built-in rule IDs and custom rule documents.
func VAP(builtin []string, docs []custom.Document, opts Options) (*Result, error) {
	if opts.ExcludeNamespaces == nil {
		opts.ExcludeNamespaces = []string{"kube-system"}
	}
	res := &Result{}
	ps := collect(builtin, docs, res)

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "# Generated by k8s-guardian export vap: ValidatingAdmissionPolicies (Kubernetes >= 1.30).")
	fmt.Fprintln(&buf, "# Apply with: kubectl apply -f <this file>")
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	for _, p := range ps {
		for _, obj := range p.objects(opts) {
			if err := enc.Encode(obj); err != nil {
				return nil, err
			}
			if obj["kind"] == "ValidatingAdmissionPolicy" {
				res.Count++
			}
		}
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	res.YAML = buf.Bytes()
	return res, nil
}

// collect resolves built-in IDs and custom documents into exportable
// policies, recording what can't be exported.
func collect(builtin []string, docs []custom.Document, res *Result) []policy {
	var ps []policy
	for _, id := range builtin {
		p, ok := builtinPolicies[strings.ToUpper(id)]
		if !ok {
			res.Skipped = append(res.Skipped, fmt.Sprintf("%s: no admission-policy equivalent (it needs cross-resource or cluster context)", id))
			continue
		}
		r := rules.Lookup(id)
		p.id, p.name, p.description, p.severity = r.ID, r.Name, r.Description, r.Severity
		ps = append(ps, p)
	}
	for _, d := range docs {
		p, err := fromCustom(d)
		if err != nil {
			res.Skipped = append(res.Skipped, fmt.Sprintf("%s (%s): %v", d.Spec.ID, d.Metadata.Name, err))
			continue
		}
		ps = append(ps, p)
	}
	return ps
}

// checks returns the (kinds, variables, expression) triples a policy is
// made of: one for resource-scoped rules, one per workload family otherwise.
type check struct {
	suffix    string
	kinds     []string
	variables []any
	expr      string
}

func (p policy) checks() []check {
	if p.scope == "resource" {
		return []check{{"", p.kinds, nil, p.expr}}
	}
	var out []check
	for _, fam := range families {
		kinds := fam.kinds
		if len(p.kinds) > 0 {
			kinds = intersect(fam.kinds, p.kinds)
		}
		if len(kinds) == 0 {
			continue
		}
		vars := []any{map[string]any{"name": "podSpec", "expression": fam.podSpec}}
		expr := p.expr
		if p.scope == "container" {
			vars = append(vars, map[string]any{"name": "containers", "expression": containersExpr})
			expr = fmt.Sprintf("variables.containers.all(c, %s)", p.expr)
		}
		out = append(out, check{fam.suffix, kinds, vars, expr})
	}
	return out
}

func (p policy) resourceName() string {
	return "k8s-guardian-" + strings.ToLower(p.id) + "-" + p.name
}

func (p policy) text() string {
	msg := p.message
	if msg == "" {
		msg = p.description
	}
	return p.id + " " + p.name + ": " + msg
}

func fromCustom(d custom.Document) (policy, error) {
	if _, err := custom.Compile(d); err != nil {
		return policy{}, err
	}
	s := d.Spec
	sev, _ := rules.ParseSeverity(s.Severity)
	p := policy{id: s.ID, name: d.Metadata.Name, description: s.Description, message: s.Message, severity: sev, scope: s.Match.Scope}
	if p.scope == "" {
		p.scope = "resource"
	}
	base := map[string]string{"resource": "object", "pod": "variables.podSpec", "container": "c"}[p.scope]
	g := &gen{}
	var when, assert []string
	for _, c := range s.When {
		e, err := g.cond(base, c)
		if err != nil {
			return p, err
		}
		when = append(when, e)
	}
	for _, c := range s.Assert {
		e, err := g.cond(base, c)
		if err != nil {
			return p, err
		}
		assert = append(assert, e)
	}
	p.expr = and(assert...)
	if len(when) > 0 {
		p.expr = or(not(and(when...)), p.expr)
	}
	if p.scope == "resource" {
		if len(s.Match.Kinds) == 0 {
			return p, fmt.Errorf("resource-scoped rules need match.kinds to be exported (matching every resource type in a cluster is unsafe)")
		}
		for _, k := range s.Match.Kinds {
			if _, ok := kindResources[k]; !ok {
				return p, fmt.Errorf("unknown kind %q for export", k)
			}
		}
		p.kinds = s.Match.Kinds
	} else {
		p.kinds = s.Match.Kinds // filters the workload families; empty = all
	}
	return p, nil
}

func (p policy) action(opts Options) string {
	if opts.Action != "" {
		return opts.Action
	}
	switch p.severity {
	case rules.Error:
		return "Deny"
	case rules.Warning:
		return "Warn"
	}
	return "Audit"
}

func resourceRules(kinds []string) []any {
	byGroup := map[string][]string{}
	for _, k := range kinds {
		r := kindResources[k]
		byGroup[r.group] = append(byGroup[r.group], r.resource)
	}
	groups := make([]string, 0, len(byGroup))
	for g := range byGroup {
		groups = append(groups, g)
	}
	sort.Strings(groups)
	var out []any
	for _, g := range groups {
		rs := byGroup[g]
		sort.Strings(rs)
		out = append(out, map[string]any{
			"apiGroups": []string{g}, "apiVersions": []string{"*"},
			"operations": []string{"CREATE", "UPDATE"}, "resources": rs,
		})
	}
	return out
}

func (p policy) objects(opts Options) []map[string]any {
	var out []map[string]any
	labels := map[string]string{"app.kubernetes.io/managed-by": "k8s-guardian", "k8s-guardian.io/rule": p.id}
	for _, c := range p.checks() {
		name := p.resourceName()
		if c.suffix != "" {
			name += "-" + c.suffix
		}
		spec := map[string]any{
			"failurePolicy":    "Fail",
			"matchConstraints": map[string]any{"resourceRules": resourceRules(c.kinds)},
			"validations":      []any{map[string]any{"expression": c.expr, "message": p.text()}},
		}
		if c.variables != nil {
			spec["variables"] = c.variables
		}
		out = append(out,
			map[string]any{
				"apiVersion": "admissionregistration.k8s.io/v1", "kind": "ValidatingAdmissionPolicy",
				"metadata": map[string]any{"name": name, "labels": labels},
				"spec":     spec,
			},
			map[string]any{
				"apiVersion": "admissionregistration.k8s.io/v1", "kind": "ValidatingAdmissionPolicyBinding",
				"metadata": map[string]any{"name": name, "labels": labels},
				"spec": map[string]any{
					"policyName":        name,
					"validationActions": []string{p.action(opts)},
					"matchResources": map[string]any{"namespaceSelector": map[string]any{"matchExpressions": []any{
						map[string]any{"key": "kubernetes.io/metadata.name", "operator": "NotIn", "values": opts.ExcludeNamespaces},
					}}},
				},
			})
	}
	return out
}

func intersect(a, b []string) []string {
	var out []string
	for _, x := range a {
		for _, y := range b {
			if strings.EqualFold(x, y) {
				out = append(out, x)
			}
		}
	}
	return out
}

// builtinPolicies are hand-written CEL equivalents of built-in rules that
// can be decided from a single object at admission time.
var builtinPolicies = map[string]policy{
	"KG001": {scope: "container", expr: `has(c.resources) && has(c.resources.requests) && 'cpu' in c.resources.requests && 'memory' in c.resources.requests`},
	"KG002": {scope: "container", expr: `has(c.resources) && has(c.resources.limits) && 'memory' in c.resources.limits`},
	"KG003": {scope: "container", expr: `(has(c.securityContext) && has(c.securityContext.runAsNonRoot)) ? c.securityContext.runAsNonRoot : ` +
		`((has(c.securityContext) && has(c.securityContext.runAsUser)) ? c.securityContext.runAsUser != 0 : ` +
		`(has(variables.podSpec.securityContext) && ((has(variables.podSpec.securityContext.runAsNonRoot) && variables.podSpec.securityContext.runAsNonRoot) || ` +
		`(has(variables.podSpec.securityContext.runAsUser) && variables.podSpec.securityContext.runAsUser != 0))))`},
	"KG004": {scope: "container", expr: `!has(c.securityContext) || !has(c.securityContext.privileged) || !c.securityContext.privileged`},
	"KG005": {scope: "container", expr: `has(c.securityContext) && has(c.securityContext.allowPrivilegeEscalation) && !c.securityContext.allowPrivilegeEscalation`},
	"KG006": {scope: "container", expr: `has(c.securityContext) && has(c.securityContext.readOnlyRootFilesystem) && c.securityContext.readOnlyRootFilesystem`},
	"KG007": {scope: "container", expr: `has(c.securityContext) && has(c.securityContext.capabilities) && has(c.securityContext.capabilities.drop) && c.securityContext.capabilities.drop.exists(d, d.upperAscii() == 'ALL')`},
	"KG010": {scope: "container", expr: `has(c.image) && (c.image.contains('@sha256:') || (c.image.substring(c.image.lastIndexOf('/') + 1).contains(':') && !c.image.endsWith(':latest')))`},
	"KG011": {scope: "pod", expr: `!(has(variables.podSpec.hostNetwork) && variables.podSpec.hostNetwork) && !(has(variables.podSpec.hostPID) && variables.podSpec.hostPID) && !(has(variables.podSpec.hostIPC) && variables.podSpec.hostIPC)`},
	"KG012": {scope: "pod", expr: `!has(variables.podSpec.volumes) || variables.podSpec.volumes.all(v, !has(v.hostPath))`},
}

// BuiltinIDs lists the built-in rules that can be exported.
func BuiltinIDs() []string {
	ids := make([]string, 0, len(builtinPolicies))
	for id := range builtinPolicies {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}
